version: '3.4'

services:
    db:
      image: favo-de-mel-sqlserver
      build:
        context: .
        dockerfile: ./Database/Dockerfile
      ports:
        - "1433:1433"

#    api:
#      image: favo-de-mel-backend
#      restart: always
#      build: ./FavoDeMel - API/
#      environment:
#        - ASPNETCORE_ENVIRONMENT=Docker
#      ports:
#        - "9000:80"
#      depends_on:
#        - db